@startuml Networking Layers

title Networking Layers

package Transformers {
	class TransportConnection {
		Tries to send data, but may mangle, drop, or duplicate it
	}
	class ReliableConnection {
		Prevents mangled, dropped, or duplicated data
	}
	class DefragmentedConnection {
		Removes fragmentation limits on message size
	}
	class EncryptedConnection {
		Prevents eavesdropping
	}
	class CompressedConnection {
		Reduces bandwidth usage
	}
	class MultiplexedConnection {
		Allows multiple connections to share the same underlying connection
	}

	TransportConnection --> ReliableConnection
	ReliableConnection --> DefragmentedConnection
	DefragmentedConnection --> EncryptedConnection
	EncryptedConnection --> CompressedConnection
	CompressedConnection --> MultiplexedConnection
}

@enduml
