/*

An audio space consists of a set of virtual audio sources and a set of physical audio sources,
as well as a set of listening volumes. The audio system places all of these within a shared
audio space, and attempts to maintain the pressure map of each listening volume as closely
as possible to the pressure map generated by the virtual audio sources.

Each virtual audio source is a spherical pressure over time map emitted from a point in space.
Each physical audio source is a physical speaker with a given position in space and measured
spherical gain map.
Each listening volume is an arbitrary volume in space with a given boundary triangle mesh,
inside of which the system attempts to maintain the calculated pressure map

The audio system is responsible for converting virtual audio sources to physical audio sources.

The audio system connects to a network of audio nodes. Each node can add or remove physical or
virtual audio sources to the shared space.

Functionality is provided to convert traditional N channel audio to a virtual audio source.
Functionality is provided to convert ambisonic audio to a virtual audio source.

*/

export * from './GainMap'
export * from './Node'
export * from './Space'
